Merge/analog to main
RadoslawSajdak/Sensors_in_embedded_systems_software pull request #12
Opened 2022-05-22 22:33 UTC by MatKozyra52

2022-05-23 22:22 UTC, RadoslawSajdak requested changes

2022-05-23 22:22 UTC, RadoslawSajdak commented on src/mq2.c
> +const double* MQ2_GAS[3] = {LPG_GAS, CO_GAS, SMOKE_GAS};
W sumie spoko
Alternatywnie można zrobić:
#define LPG_GAS {-0.47, 1.291}
...
const double MQ2_GAS[3][2] = {LPG_GAS}

Zgaduję, że inspirowane API. Różnica jest taka, że tam są struktury z różnymi dziwnymi rzeczami, a tu jest zwykła tabela stałych. Ale nie ma to chyba większego znaczenia na koniec dnia. Może jakbyś optymalizował pamięć, to oszczędzisz kilkadziesiąt bajtów robiąc "po mojemu"

2022-05-23 22:22 UTC, RadoslawSajdak commented on includes/tools.h
> +    CALIBRATION_ERROR = 9,
Init error maybe?
Generalnie dodawanie errorcode bez końca nie jest dobrym pomysłem. Tak samo to "NO_CONFIG" powinno być jako argument_error

2022-05-31 10:15 UTC, MatKozyra52 commented on Drivers/Config/Src/stm32f4xx_hal_msp.c
> +/**
w F1 to było także do F4 przepisałem z F1

2022-05-31 10:17 UTC, MatKozyra52 commented on src/adc.c
> +    hadc->Init.ClockPrescaler = ADC_CLOCK_SYNC_PCLK_DIV2;
możliwe że nie 
ustaliłem częstotliwośc w cube analogicznie do projektu i wygenerowałem config dla F4
także częstotliwości się zgadzają - co do źródła nie jestem pewien

2022-05-31 10:35 UTC, merged