Stm32f4 conf
RadoslawSajdak/Sensors_in_embedded_systems_software pull request #3
Opened 2022-05-09 22:29 UTC by MatKozyra52

2022-05-10 20:16 UTC, RadoslawSajdak requested changes
Zostawiłem sugestie w komentarzach

2022-05-10 20:16 UTC, RadoslawSajdak commented on .vscode/c_cpp_properties.json
> +        "projectPath": "/home/matkozyra52/Documents/studia/sensory/projekt/Sensors_in_embedded_systems_software"
Szanuję. Może w takim razie spróbujmy użyć tu jakiegoś pwd?

2022-05-10 20:16 UTC, RadoslawSajdak commented on .vscode/c_cpp_properties.json
> +                "STM32F4"
w takim razie, to też może niech będzie w env? Żeby nie grzebać po makefile, tylko zmieniać wszystko tam

2022-05-10 20:16 UTC, RadoslawSajdak commented on Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal.h
> +extern volatile uint32_t uwTick;
Nie powinieneś zmieniać ręcznie nic w bibliotekach hala. Chyba, że to cube nadpisał?

2022-05-10 20:16 UTC, RadoslawSajdak commented on includes/tools.h
> +#include "stm32f429xx.h"
Rozumiem intencję, ale tego typu includy powinny być w każdym pliku. Po to są te __NAME_H__, żeby kompilator się nie powtórzył. Ale my jako programiści chcemy mieć wprost pokazane że ta biblioteka, w tej sytuacji, korzysta z tego. Do "tools" można wyciągać ogólniki, jak stdint

2022-05-10 20:16 UTC, RadoslawSajdak commented on src/main.c
> +#ifdef STM32F4
To to jest w ogóle barbarzyństwo i nie ma prawa bytu w mainie. Albo w takiej sytuacji trzeba wyciągnąć funkcję SystemClock _config do osobnego pliku, albo usunąć F4 - pamiętaj, że F4 jest tylko Twoją, developerską wersją. Kod piszemy pod F103, bo on jest na pcb

2022-05-11 21:34 UTC, MatKozyra52 commented on .vscode/c_cpp_properties.json
> +        "projectPath": "/home/matkozyra52/Documents/studia/sensory/projekt/Sensors_in_embedded_systems_software"
wstawiłem zmienną ${workspaceFolder}

2022-05-12 18:55 UTC, RadoslawSajdak reviewed
Literówki do poprawy

2022-05-12 18:55 UTC, RadoslawSajdak commented on includes/bmp280.h
> +#include "stm32f1xx_hal.h"
Jesteś pewien, że nie wymaga stm32f1xx.h?

2022-05-12 18:55 UTC, RadoslawSajdak commented on src/boards.c
> +#endif //STM32F4
:)

2022-05-12 18:55 UTC, RadoslawSajdak commented on src/main.c
> +}
NL

2022-05-12 19:16 UTC, merged